#!/usr/bin/env node
/**
 * Generate `src/generated/index.ts` from the desktop's embedded control icons
 * (`crates/ui/assets/icons/*.svg`) — the same assets `crates/ui/src/icons.rs`
 * compiles in. Parity is by construction: the web client never hand-draws a
 * glyph the desktop does not have, and a changed asset changes both clients.
 *
 *   node scripts/generate.mjs            # write
 *   node scripts/generate.mjs --check    # fail when stale (no CI gate runs
 *                                         # this — regeneration is manual)
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../../../..");
const assetDir = join(repoRoot, "crates/ui/assets/icons");
const outDir = join(here, "../src/generated");
const outFile = join(outDir, "index.ts");

/** `alt-arrow-down.svg` -> `altArrowDown`. */
const camel = (name) => name.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());

/**
 * Root-stroke carry: these presentation attributes are read off the root
 * `<svg>` and re-emitted on every shape element that does not carry its
 * own. The body is injected via `dangerouslySetInnerHTML`, so a root-only
 * stroke does not survive and the glyph would paint nothing.
 */
const STROKE_ATTRS = ["stroke", "stroke-width", "stroke-linecap", "stroke-linejoin"];
const SHAPE_TAGS = ["path", "circle", "ellipse", "rect", "line", "polyline", "polygon", "text", "use"];

/** Pull the root `<svg …>` attributes and its inner markup. */
function parse(source) {
  const open = source.match(/<svg\b([^>]*)>/);
  if (!open) {
    throw new Error("no <svg> root");
  }
  const attrs = Object.fromEntries(
    [...open[1].matchAll(/([a-zA-Z:-]+)\s*=\s*"([^"]*)"/g)].map((m) => [m[1], m[2]]),
  );
  let body = source
    .slice(open.index + open[0].length, source.lastIndexOf("</svg>"))
    .replace(/\s+/g, " ")
    .trim();
  const rootStrokes = STROKE_ATTRS.filter((name) => attrs[name] !== undefined);
  if (rootStrokes.length > 0) {
    const shapeTag = new RegExp(`<(${SHAPE_TAGS.join("|")})\\b([^>]*)>`, "g");
    body = body.replace(shapeTag, (tag, name, rest) => {
      const selfClose = rest.endsWith("/");
      const attrText = (selfClose ? rest.slice(0, -1) : rest).replace(/\s+$/, "");
      const own = new Set([...attrText.matchAll(/([a-zA-Z:-]+)\s*=/g)].map((m) => m[1]));
      const carried = rootStrokes.filter((attrName) => !own.has(attrName));
      if (carried.length === 0) {
        return tag;
      }
      const extra = carried.map((attrName) => ` ${attrName}="${attrs[attrName]}"`).join("");
      return `<${name}${attrText}${extra}${selfClose ? "/" : ""}>`;
    });
  }
  return { viewBox: attrs.viewBox ?? "0 0 24 24", fill: attrs.fill ?? "none", body };
}

const entries = readdirSync(assetDir)
  .filter((file) => file.endsWith(".svg"))
  .sort()
  .map((file) => {
    const slug = file.slice(0, -4);
    const { viewBox, fill, body } = parse(readFileSync(join(assetDir, file), "utf8"));
    // The root-paint floor: a glyph whose root fill is `none` and whose
    // body carries no `stroke=`/`fill=` (and no embedded raster) renders
    // invisible — fail the run instead of committing it.
    if (fill === "none" && !body.includes("stroke=") && !body.includes("fill=") && !body.includes("<image")) {
      throw new Error(`${file}: root paints nothing (fill="none", no stroke/fill in the body)`);
    }
    return { key: camel(slug), slug, viewBox, fill, body };
  });

const lines = [
  "// @generated by web/packages/icons/scripts/generate.mjs — do not edit.",
  "// Source: crates/ui/assets/icons/*.svg (the assets crates/ui/src/icons.rs embeds).",
  "",
  "export interface IconAsset {",
  "  /** Root `viewBox`, verbatim from the asset. */",
  "  readonly viewBox: string;",
  "  /** Root `fill`, verbatim — `none` for stroked Solar glyphs. */",
  "  readonly fill: string;",
  "  /** Inner markup; every paint is `currentColor`, so the glyph tints with `color`. */",
  "  readonly body: string;",
  "}",
  "",
  "export const iconAssets = {",
  ...entries.map(
    (e) =>
      `  ${e.key}: { viewBox: ${JSON.stringify(e.viewBox)}, fill: ${JSON.stringify(e.fill)}, body: ${JSON.stringify(e.body)} },`,
  ),
  "} as const satisfies Record<string, IconAsset>;",
  "",
  "export type IconName = keyof typeof iconAssets;",
  "",
];
const next = lines.join("\n");

if (process.argv.includes("--check")) {
  const current = existsSync(outFile) ? readFileSync(outFile, "utf8") : "";
  if (current !== next) {
    console.error(
      "@zeron/icons is stale — run `pnpm --filter @zeron/icons regenerate` and commit the result.",
    );
    process.exit(1);
  }
  console.log(`@zeron/icons is fresh (${entries.length} glyphs).`);
} else {
  mkdirSync(outDir, { recursive: true });
  writeFileSync(outFile, next);
  console.log(`wrote ${outFile} (${entries.length} glyphs)`);
}
