//! macOS Seatbelt: an SBPL profile run through `/usr/bin/sandbox-exec`.
//!
//! Unlike Codex and Claude Code, which confine the *tool commands* their
//! agent runs, Zeron confines the agent CLI itself (its tools and
//! subagents inherit the profile). So the profile keeps Codex's closed-by-
//! default shape but adds what a Node/Bun or Rust CLI needs to run, log in
//! and talk TLS: the Keychain (`SecurityServer`), trust evaluation, DNS
//! configuration. Sources, both Apache-2.0 and both descended from
//! Chromium's sandbox policy:
//!
//! - OpenAI Codex, `codex-rs/sandboxing/src/seatbelt_base_policy.sbpl` and
//!   `seatbelt_network_policy.sbpl` (process, sysctl, pty, device and
//!   platform rules; the fcntl deny; protecting ancestors of carve-outs
//!   against rename).
//! - Anthropic `sandbox-runtime`, `src/sandbox/macos-sandbox-utils.ts`
//!   (mach-lookup and IOKit allow list for Node, loopback rules and why
//!   bind/inbound use `local ip`, string escaping).
//!
//! Rule order matters: Seatbelt applies the *last* matching rule, so the
//! profile goes broad → narrow: allow reads, allow writes to the writable
//! roots, deny writes to read-only carve-outs, deny everything on hidden
//! paths.

use std::path::{Path, PathBuf};

use crate::{Backend, Enforcement, Resolved, SandboxError, SandboxMode};

/// Only ever `/usr/bin/sandbox-exec`, never one found on `PATH`.
pub(crate) const SANDBOX_EXEC: &str = "/usr/bin/sandbox-exec";

pub(crate) fn available() -> bool {
    Path::new(SANDBOX_EXEC).exists()
}

pub(crate) fn enforcement(r: &Resolved) -> Enforcement {
    let mut notes = Vec::new();
    if !r.network {
        notes.push(
            "network off still allows loopback (any port), so the agent reaches Zeron's MCP \
             server and servers it starts itself"
                .into(),
        );
    }
    Enforcement {
        backend: Backend::Seatbelt,
        writes: true,
        hidden: true,
        read_only: true,
        network: true,
        notes,
    }
}

const BASE: &str = r#"(version 1)
; Generated by zeron-sandbox (crates/sandbox/src/seatbelt.rs). Adapted from
; OpenAI Codex's seatbelt_base_policy.sbpl and Anthropic's sandbox-runtime
; macOS profile (both Apache-2.0, both after Chromium's sandbox policy).
(deny default)

; Processes. Children inherit this profile.
(allow process-exec)
(allow process-fork)
(allow signal (target same-sandbox))
(allow process-info* (target same-sandbox))
(allow mach-priv-task-port (target same-sandbox))

; System information and preferences.
(allow sysctl-read)
(allow sysctl-write
  (sysctl-name "kern.grade_cputype")
  (sysctl-name "kern.tcsm_enable"))
(allow user-preference-read)
(allow ipc-posix-shm)
(allow ipc-posix-sem)
(allow iokit-open
  (iokit-registry-entry-class "IOSurfaceRootUserClient")
  (iokit-registry-entry-class "RootDomainUserClient")
  (iokit-user-client-class "IOSurfaceSendRight"))
(allow iokit-get-properties)
(allow system-socket (require-all (socket-domain AF_SYSTEM) (socket-protocol 2)))
(allow distributed-notification-post)
(allow system-mac-syscall (mac-policy-name "vnguard"))
(allow system-mac-syscall (require-all (mac-policy-name "Sandbox") (mac-syscall-number 67)))
(allow system-fsctl (fsctl-command FSIOC_CAS_BSDFLAGS))

; Mach services: user/group lookup, logging, preferences, the Keychain
; (agent logins), certificate trust and network configuration (TLS).
; launchservicesd/lsopen and Apple Events stay closed: `open` and
; `osascript` would start programs outside the sandbox.
(allow mach-lookup
  (global-name "com.apple.analyticsd")
  (global-name "com.apple.audio.systemsoundserver")
  (global-name "com.apple.bsd.dirhelper")
  (global-name "com.apple.cfprefsd.agent")
  (global-name "com.apple.cfprefsd.daemon")
  (global-name "com.apple.diagnosticd")
  (global-name "com.apple.distributed_notifications@Uv3")
  (global-name "com.apple.FontObjectsServer")
  (global-name "com.apple.fonts")
  (global-name "com.apple.logd")
  (global-name "com.apple.lsd.mapdb")
  (global-name "com.apple.networkd")
  (global-name "com.apple.ocspd")
  (global-name "com.apple.PowerManagement.control")
  (global-name "com.apple.SecurityServer")
  (global-name "com.apple.securityd.xpc")
  (global-name "com.apple.system.logger")
  (global-name "com.apple.system.notification_center")
  (global-name "com.apple.system.opendirectoryd.libinfo")
  (global-name "com.apple.system.opendirectoryd.membership")
  (global-name "com.apple.SystemConfiguration.configd")
  (global-name "com.apple.SystemConfiguration.DNSConfiguration")
  (global-name "com.apple.trustd")
  (global-name "com.apple.trustd.agent")
  (global-name "com.apple.TrustEvaluationAgent")
  (local-name "com.apple.cfprefsd.agent"))

; Terminals: ptys the agent opens itself (they carry the pty extension), and
; ioctl on ones it inherited so shells detect a TTY.
(allow pseudo-tty)
(allow file-read* file-write* file-ioctl (literal "/dev/ptmx"))
(allow file-read* file-write*
  (require-all
    (regex #"^/dev/ttys[0-9]+$")
    (extension "com.apple.sandbox.pty")))
(allow file-ioctl (regex #"^/dev/ttys[0-9]+$"))

; Devices.
(allow file-write-data file-ioctl
  (literal "/dev/null")
  (literal "/dev/zero")
  (literal "/dev/dtracehelper")
  (literal "/dev/tty"))
(allow file-read-data file-write-data file-ioctl (subpath "/dev/fd"))

; These fcntls change files through read-only descriptors
; (F_MAKECOMPRESSED = 80, F_TRANSFEREXTENTS = 110).
(deny system-fcntl (fcntl-command 80 110))

; Reading is allowed everywhere except the hidden paths at the end.
(allow file-read*)
"#;

/// The SBPL profile for `r`.
pub(crate) fn profile(r: &Resolved) -> Result<String, SandboxError> {
    let mut p = String::from(BASE);

    p.push_str("\n; Writable: ");
    p.push_str(match r.mode {
        SandboxMode::WorkspaceWrite => "the workspace, temp folders and the agent's state.\n",
        _ => "temp folders and the agent's state (the workspace is read-only).\n",
    });
    let mut filters = Vec::new();
    for path in &r.write {
        filters.push(format!("(subpath {})", string(path)?));
    }
    for path in &r.write_prefixes {
        filters.push(format!("(prefix {})", string(path)?));
    }
    push_rule(&mut p, "(allow file-write*", &filters);

    if !r.read_only.is_empty() {
        p.push_str("\n; Read-only inside the writable areas.\n");
        let filters = r
            .read_only
            .iter()
            .map(|path| Ok(format!("(subpath {})", string(path)?)))
            .collect::<Result<Vec<_>, SandboxError>>()?;
        push_rule(&mut p, "(deny file-write*", &filters);
    }

    let ancestors = r.protected_ancestors();
    if !ancestors.is_empty() {
        p.push_str("\n; Renaming a folder above a protected path would carry it out from\n");
        p.push_str("; under its rule.\n");
        for path in &ancestors {
            p.push_str(&format!(
                "(deny file-write-unlink (require-all (vnode-type DIRECTORY) (literal {})))\n",
                string(path)?
            ));
        }
    }

    p.push('\n');
    p.push_str(&network(r)?);

    if !r.hidden.is_empty() {
        p.push_str("\n; Hidden: neither readable nor writable, whatever allowed it above.\n");
        let filters = r
            .hidden
            .iter()
            .map(|path| Ok(format!("(subpath {})", string(path)?)))
            .collect::<Result<Vec<_>, SandboxError>>()?;
        push_rule(&mut p, "(deny file-read* file-write*", &filters);
    }
    Ok(p)
}

fn network(r: &Resolved) -> Result<String, SandboxError> {
    if r.network {
        return Ok("; Network: on.\n(allow network*)\n(allow system-socket)\n".into());
    }
    let mut p = String::from(
        "; Network: off, except loopback (Zeron's MCP server, local dev servers).\n\
         ; bind/inbound use `local ip`: IPv6 dual-stack sockets bound to 127.0.0.1\n\
         ; show up as ::ffff:127.0.0.1, which the `localhost` host doesn't match\n\
         ; (sandbox-runtime #225). Outbound stays `remote ip \"localhost:*\"`.\n\
         (allow system-socket (socket-domain AF_INET))\n\
         (allow system-socket (socket-domain AF_INET6))\n\
         (allow network-bind (local ip \"localhost:*\"))\n\
         (allow network-inbound (local ip \"localhost:*\"))\n\
         (allow network-outbound (remote ip \"localhost:*\"))\n",
    );
    // Unix sockets only inside the writable roots (the agent's own servers,
    // language servers, tmux…), not the user's agents and daemons.
    let roots: Vec<&PathBuf> = r.write.iter().collect();
    if !roots.is_empty() {
        p.push_str("(allow system-socket (socket-domain AF_UNIX))\n");
        let mut filters = Vec::new();
        for root in roots {
            filters.push(format!("(local unix-socket (subpath {}))", string(root)?));
        }
        push_rule(&mut p, "(allow network-bind", &filters);
        let filters = r
            .write
            .iter()
            .map(|root| Ok(format!("(remote unix-socket (subpath {}))", string(root)?)))
            .collect::<Result<Vec<_>, SandboxError>>()?;
        push_rule(&mut p, "(allow network-outbound", &filters);
    }
    Ok(p)
}

fn push_rule(p: &mut String, head: &str, filters: &[String]) {
    if filters.is_empty() {
        return;
    }
    p.push_str(head);
    for f in filters {
        p.push_str("\n  ");
        p.push_str(f);
    }
    p.push_str(")\n");
}

/// `path` as an SBPL string literal. Backslashes and double quotes are
/// escaped; control characters (and non-UTF-8) are refused rather than
/// guessed at.
pub(crate) fn string(path: &Path) -> Result<String, SandboxError> {
    let s = path
        .to_str()
        .ok_or_else(|| SandboxError::UnsupportedPath(path.to_path_buf()))?;
    if s.chars().any(char::is_control) {
        return Err(SandboxError::UnsupportedPath(path.to_path_buf()));
    }
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        if c == '"' || c == '\\' {
            out.push('\\');
        }
        out.push(c);
    }
    out.push('"');
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::SandboxSpec;

    fn resolved(mode: SandboxMode, network: bool) -> Resolved {
        let spec = SandboxSpec {
            mode,
            network,
            workspace: "/zeron-test/home/proj".into(),
            writable: vec!["/zeron-test/home/.claude".into()],
            writable_prefixes: vec!["/zeron-test/home/.claude.json".into()],
            read_only: vec![
                "/zeron-test/home/proj/.git/hooks".into(),
                "/zeron-test/home/.claude/settings.json".into(),
            ],
            hidden: vec![
                "/zeron-test/home/.ssh".into(),
                "/zeron-test/home/proj/.env.secret".into(),
            ],
            loopback_ports: vec![27654],
        };
        Resolved::new(&spec, vec!["/zeron-test/tmp".into()]).unwrap()
    }

    /// The parts after the fixed base, which is checked separately.
    fn tail(profile: &str) -> &str {
        profile
            .strip_prefix(BASE)
            .expect("profile starts with the base")
    }

    #[test]
    fn golden_workspace_write_network_off() {
        let p = profile(&resolved(SandboxMode::WorkspaceWrite, false)).unwrap();
        assert_eq!(
            tail(&p),
            r#"
; Writable: the workspace, temp folders and the agent's state.
(allow file-write*
  (subpath "/zeron-test/home/.claude")
  (subpath "/zeron-test/home/proj")
  (subpath "/zeron-test/tmp")
  (prefix "/zeron-test/home/.claude.json"))

; Read-only inside the writable areas.
(deny file-write*
  (subpath "/zeron-test/home/.claude/settings.json")
  (subpath "/zeron-test/home/proj/.git/hooks"))

; Renaming a folder above a protected path would carry it out from
; under its rule.
(deny file-write-unlink (require-all (vnode-type DIRECTORY) (literal "/zeron-test/home/proj/.git")))

; Network: off, except loopback (Zeron's MCP server, local dev servers).
; bind/inbound use `local ip`: IPv6 dual-stack sockets bound to 127.0.0.1
; show up as ::ffff:127.0.0.1, which the `localhost` host doesn't match
; (sandbox-runtime #225). Outbound stays `remote ip "localhost:*"`.
(allow system-socket (socket-domain AF_INET))
(allow system-socket (socket-domain AF_INET6))
(allow network-bind (local ip "localhost:*"))
(allow network-inbound (local ip "localhost:*"))
(allow network-outbound (remote ip "localhost:*"))
(allow system-socket (socket-domain AF_UNIX))
(allow network-bind
  (local unix-socket (subpath "/zeron-test/home/.claude"))
  (local unix-socket (subpath "/zeron-test/home/proj"))
  (local unix-socket (subpath "/zeron-test/tmp")))
(allow network-outbound
  (remote unix-socket (subpath "/zeron-test/home/.claude"))
  (remote unix-socket (subpath "/zeron-test/home/proj"))
  (remote unix-socket (subpath "/zeron-test/tmp")))

; Hidden: neither readable nor writable, whatever allowed it above.
(deny file-read* file-write*
  (subpath "/zeron-test/home/.ssh")
  (subpath "/zeron-test/home/proj/.env.secret"))
"#
        );
    }

    #[test]
    fn golden_read_only_network_on() {
        let p = profile(&resolved(SandboxMode::ReadOnly, true)).unwrap();
        assert_eq!(
            tail(&p),
            r#"
; Writable: temp folders and the agent's state (the workspace is read-only).
(allow file-write*
  (subpath "/zeron-test/home/.claude")
  (subpath "/zeron-test/tmp")
  (prefix "/zeron-test/home/.claude.json"))

; Read-only inside the writable areas.
(deny file-write*
  (subpath "/zeron-test/home/.claude/settings.json"))

; Network: on.
(allow network*)
(allow system-socket)

; Hidden: neither readable nor writable, whatever allowed it above.
(deny file-read* file-write*
  (subpath "/zeron-test/home/.ssh")
  (subpath "/zeron-test/home/proj/.env.secret"))
"#
        );
    }

    #[test]
    fn base_is_closed_by_default_and_never_opens_launch_services() {
        assert!(BASE.contains("(deny default)"));
        for forbidden in [
            "(allow lsopen",
            "(allow appleevent-send",
            "\"com.apple.coreservices.launchservicesd\"",
            "\"com.apple.coreservices.appleevents\"",
            "(allow file-write*)",
            "(allow network",
            "(allow default",
        ] {
            assert!(!BASE.contains(forbidden), "base profile allows {forbidden}");
        }
    }

    #[test]
    fn strings_escape_quotes_and_backslashes() {
        assert_eq!(string(Path::new("/a b/c")).unwrap(), r#""/a b/c""#);
        assert_eq!(
            string(Path::new(r#"/we"ird\dir"#)).unwrap(),
            r#""/we\"ird\\dir""#
        );
        assert_eq!(string(Path::new("/ünï/ç😀")).unwrap(), "\"/ünï/ç😀\"");
        assert!(matches!(
            string(Path::new("/new\nline")),
            Err(SandboxError::UnsupportedPath(_))
        ));
        // A path that tries to close the string and inject a rule stays one
        // literal.
        assert_eq!(
            string(Path::new(r#"/x") (allow default) ("#)).unwrap(),
            r#""/x\") (allow default) (""#
        );
    }
}
