import type { Appearance } from "@zeron/theme";
import { fileIconManifest } from "@zeron/icons/generated/file-icons";

/**
 * The file-type icon resolver — a port of `crates/ui/src/file_icons.rs`.
 *
 * Every resolved icon is an asset path under a fixed root-absolute
 * `/file-icons/` prefix (`ASSET_PREFIX`), with `dark/` inserted for the dark
 * appearance: dark mode is a *different asset path*
 * (`/file-icons/dark/files/rust.svg` vs `/file-icons/files/rust.svg`),
 * which is what forces a fresh image load on
 * theme switch. The assets themselves are generated by
 * `web/packages/icons/scripts/generate-file-icons.mjs` from the desktop's
 * artwork (the dark tree applies the seven accent lifts at generate time);
 * this module only resolves names against the generated manifest.
 *
 * Resolution preserves the VS Code theme's semantics (file_icons.rs):
 * exact basenames win, then the longest matching compound extension, then
 * an optional syntax-language or MIME hint, then the generic file/folder
 * icon.
 */

/**
 * `file_icons.rs::ASSET_PREFIX` — root-absolute, like the desktop's gpui
 * asset namespace: a leading `/` resolves against the site root on every
 * route, where a document-relative reference would re-base onto `/chat/`
 * and 404 past the engine's static bundle.
 */
const ASSET_PREFIX = "/file-icons/";

/** The hard fallbacks when the manifest itself has no answer. */
const GENERIC_FILE_ASSET = "files/document.svg";
const GENERIC_FOLDER_ASSET = "folders/folder.svg";

/**
 * The syntax-language hint the desktop threads through
 * `FileIconIdentity::with_language` — the web spelling of
 * `zeron_syntax::LanguageId`'s variant names. Not needed by the tree (no
 * language is known there); ticket 25's editor breadcrumb uses it.
 */
export type FileIconLanguage =
  | "Rust"
  | "JavaScript"
  | "Jsx"
  | "TypeScript"
  | "Tsx"
  | "Python"
  | "Go"
  | "Json"
  | "Jsonc"
  | "Bash"
  | "Toml"
  | "Markdown"
  | "Html"
  | "Css"
  | "Yaml"
  | "C"
  | "Cpp"
  | "CSharp"
  | "Java"
  | "Kotlin"
  | "Swift"
  | "Ruby"
  | "Php"
  | "Sql"
  | "Lua"
  | "Dockerfile"
  | "Nix"
  | "Make";

/** Optional hints for `resolveFileIcon` (steps 4-5 of the order). */
export interface FileIconHints {
  readonly language?: FileIconLanguage;
  readonly mimeType?: string;
}

function lowercaseKeys(values: Readonly<Record<string, string>>): Map<string, string> {
  const out = new Map<string, string>();
  for (const [key, value] of Object.entries(values)) {
    out.set(key.toLowerCase(), value);
  }
  return out;
}

// `lowercase_keys` at load time: the three lookup maps become
// case-insensitive; `iconDefinitions`/`languageIds` stay as authored.
const definitions: ReadonlyMap<string, string> = new Map(
  Object.entries(fileIconManifest.iconDefinitions).map(([name, def]) => [name, def.iconPath]),
);
const fileExtensions = lowercaseKeys(fileIconManifest.fileExtensions);
const fileNames = lowercaseKeys(fileIconManifest.fileNames);
const folderNames = lowercaseKeys(fileIconManifest.folderNames);
const languageIds: ReadonlyMap<string, string> = new Map(Object.entries(fileIconManifest.languageIds));

/** `file_icons.rs::definition_asset` — name → `"./icons/"`-stripped asset. */
function definitionAsset(definition: string): string | null {
  // Two identifiers are referenced by the manifest but have no icon
  // definition of their own; their language associations reveal the
  // intended aliases, so resolve them rather than falling back.
  const aliased =
    definition === "less" ? "brackets-sky" : definition === "yml" ? "yaml" : definition;
  const iconPath = definitions.get(aliased);
  return iconPath?.startsWith("./icons/") ? iconPath.slice("./icons/".length) : null;
}

/** `file_icons.rs::basename` — both separators, like the Rust. */
function basename(path: string): string {
  const slash = Math.max(path.lastIndexOf("/"), path.lastIndexOf("\\"));
  return slash >= 0 ? path.slice(slash + 1) : path;
}

/** `compound_extensions`: every suffix after each `.`, longest first. */
function compoundExtensions(name: string): string[] {
  const out: string[] = [];
  let index = name.indexOf(".");
  while (index >= 0) {
    const extension = name.slice(index + 1);
    if (extension.length > 0) {
      out.push(extension);
    }
    index = name.indexOf(".", index + 1);
  }
  return out;
}

/** `generic_file_asset` — the manifest's `file`, else the hardcoded fallback. */
function genericFileAsset(): string {
  if (fileIconManifest.file !== null) {
    const asset = definitionAsset(fileIconManifest.file);
    if (asset !== null) {
      return asset;
    }
  }
  return GENERIC_FILE_ASSET;
}

/**
 * `asset_path`'s variant half: `/file-icons/` + `dark/` (dark appearance) +
 * the asset. A resolved asset is always one of the generated public files.
 */
export function fileIconAssetPath(asset: string, appearance: Appearance): string {
  const variant = appearance === "dark" ? "dark/" : "";
  return `${ASSET_PREFIX}${variant}${asset}`;
}

/**
 * `resolve_file` (steps 2-6): exact lowercased basename, longest compound
 * extension, language hint, MIME hint, generic fallback. The tree and search
 * rows call this with no hints.
 */
export function resolveFileIcon(path: string, appearance: Appearance, hints?: FileIconHints): string {
  const name = basename(path).toLowerCase();
  let asset: string | null = null;
  const fileNameDefinition = fileNames.get(name);
  if (fileNameDefinition !== undefined) {
    asset = definitionAsset(fileNameDefinition);
  }
  if (asset === null) {
    for (const extension of compoundExtensions(name)) {
      const definition = fileExtensions.get(extension.toLowerCase());
      if (definition !== undefined) {
        asset = definitionAsset(definition);
        if (asset !== null) {
          break;
        }
      }
    }
  }
  if (asset === null) {
    asset = languageAsset(hints?.language) ?? mimeAsset(hints?.mimeType);
  }
  return fileIconAssetPath(asset ?? genericFileAsset(), appearance);
}

/**
 * `resolve_directory` (step 1): exact lowercased name match, else the
 * manifest's generic `folder`, else the hardcoded fallback. There is no
 * separate open/closed icon — `expanded` is threaded for the caller's
 * chevron glyph, but the folder image is identical either way.
 */
export function resolveDirectoryIcon(name: string, appearance: Appearance, _expanded?: boolean): string {
  const definition = folderNames.get(name.toLowerCase()) ?? fileIconManifest.folder ?? null;
  const asset = definition !== null ? definitionAsset(definition) : null;
  return fileIconAssetPath(asset ?? GENERIC_FOLDER_ASSET, appearance);
}

/** `language_asset` — the fixed LanguageId → definition table. */
function languageAsset(language: FileIconLanguage | undefined): string | null {
  if (language === undefined) {
    return null;
  }
  let definition: string;
  switch (language) {
    case "Rust":
      definition = "rust";
      break;
    case "JavaScript":
      definition = "javascript";
      break;
    case "Jsx":
      definition = "javascriptreact";
      break;
    case "TypeScript":
      definition = "typescript";
      break;
    case "Tsx":
      definition = "typescriptreact";
      break;
    case "Python":
      definition = "python";
      break;
    case "Go":
      definition = "go";
      break;
    case "Json":
    case "Jsonc":
      definition = "json";
      break;
    case "Bash":
      definition = "shellscript";
      break;
    case "Toml":
      // No languageId — the definition directly.
      return definitionAsset("gear");
    case "Markdown":
      definition = "markdown";
      break;
    case "Html":
      definition = "html";
      break;
    case "Css":
      definition = "css";
      break;
    case "Yaml":
      definition = "yaml";
      break;
    case "C":
      definition = "c";
      break;
    case "Cpp":
      definition = "cpp";
      break;
    case "CSharp":
      definition = "csharp";
      break;
    case "Java":
      definition = "java";
      break;
    case "Kotlin":
      return definitionAsset("kotlin");
    case "Swift":
      definition = "swift";
      break;
    case "Ruby":
      definition = "ruby";
      break;
    case "Php":
      definition = "php";
      break;
    case "Sql":
      definition = "sql";
      break;
    case "Lua":
      definition = "lua";
      break;
    case "Dockerfile":
      definition = "dockerfile";
      break;
    case "Nix":
      definition = "nix";
      break;
    case "Make":
      definition = "makefile";
      break;
  }
  const asset = languageIds.get(definition);
  return asset !== undefined ? definitionAsset(asset) : null;
}

/** `mime_asset` — parameter stripped, lowercased, prefix/exact matches. */
function mimeAsset(mimeType: string | undefined): string | null {
  if (mimeType === undefined) {
    return null;
  }
  const type = mimeType.split(";")[0]?.trim().toLowerCase() ?? "";
  let definition: string;
  if (type.startsWith("image/")) {
    definition = "image";
  } else if (type.startsWith("audio/")) {
    definition = "audio";
  } else if (type.startsWith("video/")) {
    definition = "video";
  } else {
    switch (type) {
      case "application/json":
      case "application/ld+json":
        definition = "brackets-yellow";
        break;
      case "application/pdf":
        definition = "pdf";
        break;
      case "application/zip":
      case "application/gzip":
      case "application/x-tar":
        definition = "compressed";
        break;
      case "text/markdown":
        definition = "markdown";
        break;
      case "text/css":
        definition = "brackets-sky";
        break;
      case "text/html":
        definition = "brackets-orange";
        break;
      default:
        return null;
    }
  }
  return definitionAsset(definition);
}

/**
 * `has_specific_file_icon` — the stricter check prose renderers use to
 * decide whether a bare filename mention deserves a decorative icon: true
 * only when resolution would return something other than the generic
 * document icon. Language and MIME hints are not consulted.
 */
export function hasSpecificFileIcon(path: string): boolean {
  const name = basename(path).toLowerCase();
  if (fileNames.get(name) !== undefined) {
    return true;
  }
  for (const extension of compoundExtensions(name)) {
    if (fileExtensions.get(extension.toLowerCase()) !== undefined) {
      return true;
    }
  }
  return false;
}

/**
 * `well_bg` — a neutral backdrop a caller can place behind a polychrome
 * icon so it stays legible regardless of the surrounding surface. Not used
 * by tree/search rows (they render icons directly on the row background,
 * like the desktop); exported for later call sites.
 */
export function wellBg(appearance: Appearance, frosted: boolean): string {
  const alpha = frosted ? 0.32 : 0.16;
  return appearance === "dark"
    ? `rgb(0 0 0 / ${alpha})`
    : `rgb(255 255 255 / ${alpha})`;
}
